GROUP BY DATE RANGE

- means group data basedon time periods like :

- per day/week/month/blw 2 dates

EXAMPLE :

- jan total sales : 5000

- feb total sales : 7000

In [1]:
import pandas as pd
data={
    "date":[
        "2024-01-01",
        "2024-01-05",
        "2024-02-10",
        "2024-02-15",
        "2024-03-20"
    ],
    "sales":[100,200,150,300,250]
}
df=pd.DataFrame(data)
df["date"]=pd.to_datetime(df["date"])
print(df)

        date  sales
0 2024-01-01    100
1 2024-01-05    200
2 2024-02-10    150
3 2024-02-15    300
4 2024-03-20    250

In [5]:
df.groupby(df["date"].dt.month)["sales"].sum()

date
1    300
2    450
3    250
Name: sales, dtype: int64

In [13]:
# grp by date range using resample()
# frst set data as index
#df.set_index("date",inplace=True) 
df.resample("ME").sum()

            sales
date
2024-01-31    300
2024-02-29    450
2024-03-31    250

In [ ]:
# CUSTOM DATE RANGE GROUPING
df["period"]=pd.cut(
    df.index,
    bins=[                                      # bins : intervels
        pd.Timestamp("2024-01-01"),             # Timestamp : is a datetime object,which pandas understands for date comparision
        pd.Timestamp("2024-03-01"),
        pd.Timestamp("2024-05-01")
    ],
    labels=["jan-feb","mar-apr"]
)
df.groupby("period")["sales"].sum()

period
jan-feb    650
mar-apr    250
Name: sales, dtype: int64

PRACTICE

In [15]:
import pandas as pd
data={
    "date":[
        "2024-01-01",
        "2024-01-10",
        "2024-02-05",
        "2024-02-20",
        "2024-03-01"
    ],
    "sales":[80,90,85,70,95]
}
df=pd.DataFrame(data)
df["date"]=pd.to_datetime(df["date"])

In [16]:
#1 group total sales by month
df.groupby(df["date"].dt.month)["sales"].sum()

date
1    170
2    155
3     95
Name: sales, dtype: int64

In [17]:
#2 group total sales by year
df.groupby(df["date"].dt.year)["sales"].sum()

date
2024    420
Name: sales, dtype: int64

In [18]:
#3 find avg sales per month
df.groupby(df["date"].dt.month)["sales"].mean()

date
1    85.0
2    77.5
3    95.0
Name: sales, dtype: float64

In [20]:
#4 count no of sale records per month
df.groupby(df["date"].dt.month)["sales"].count()

date
1    2
2    2
3    1
Name: sales, dtype: int64

In [21]:
#5 find max sales in each month
df.groupby(df["date"].dt.month)["sales"].max()

date
1    90
2    85
3    95
Name: sales, dtype: int64

In [24]:
#6 set date as index and find monthly total sales
df.set_index("date",inplace=True) 
df.resample("ME").sum()

            sales
date
2024-01-31    170
2024-02-29    155
2024-03-31     95

In [25]:
#7 find weekly total sales
df.resample("W").sum()

            sales
date
2024-01-07     80
2024-01-14     90
2024-01-21      0
2024-01-28      0
2024-02-04      0
2024-02-11     85
2024-02-18      0
2024-02-25     70
2024-03-03     95

In [27]:
#8 find monthly avg sales
df.resample("ME").mean()

            sales
date
2024-01-31   85.0
2024-02-29   77.5
2024-03-31   95.0

In [28]:
#9 find no of sales per month
df.resample("ME").count()

            sales
date
2024-01-31      2
2024-02-29      2
2024-03-31      1

In [29]:
data={
    "date":[
        "2024-01-01",
        "2024-01-10",
        "2024-02-05",
        "2024-02-20",
        "2024-03-01"
    ],
    "city":[
        "delhi",
        "mumbai",
        "delhi",
        "mumbai",
        "delhi"
    ],
    "sales":[100,200,150,300,250]
}
df=pd.DataFrame(data)
df["date"]=pd.to_datetime(df["date"])

In [31]:
#10 find monthly total sales using grouper
df.groupby(pd.Grouper(key="date",freq="ME"))["sales"].sum()

date
2024-01-31    300
2024-02-29    450
2024-03-31    250
Freq: ME, Name: sales, dtype: int64