In [1]:
# create array
import numpy as np
arr=np.array([10,20,30,40,50])

In [8]:
# find mean and sum
import numpy as np
arr=np.array([5,10,15,20])
np.mean(arr)
np.sum(arr)

np.int64(50)

In [10]:
# reshape
arr=np.array([1,2,3,4])
arr.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [11]:
# create dataframe
import pandas as pd
data={
    "name":["ram","sam","tom"],
    "marks":[80,90,85]
}
df=pd.DataFrame(data)

In [12]:
# filter students
df[df["marks"]>80]

  name  marks
1  sam     90
2  tom     85

In [20]:
# replace missing values with 0
df.fillna(0)

  name  marks
0  ram     80
1  sam     90
2  tom     85

In [13]:
# find avg marks by name
df.groupby("name").mean()

      marks
name
ram    80.0
sam    90.0
tom    85.0

In [14]:
# find max marks
df["marks"].max()

np.int64(90)

In [16]:
# count students
len(df)

3

In [21]:
df.sort_values("marks")

  name  marks
0  ram     80
2  tom     85
1  sam     90

In [22]:
# show first 2 rows of df
df.head(2)

  name  marks
0  ram     80
1  sam     90

In [24]:
# show col names
df.columns

Index(['name', 'marks'], dtype='str')

In [29]:
# check missing values
df.isnull()

    name  marks
0  False  False
1  False  False
2  False  False

In [25]:
df.drop_duplicates()

  name  marks
0  ram     80
1  sam     90
2  tom     85

In [30]:
df["marks"]

0    80
1    90
2    85
Name: marks, dtype: int64

In [31]:
# show last 2 rows
df.tail(2)

  name  marks
1  sam     90
2  tom     85

In [33]:
# get no of rows & col
df.shape

(3, 2)

In [39]:
# sort marks in descending order
df.sort_values("marks",ascending=False)

  name  marks grades
1  sam     90      B
2  tom     85      C
0  ram     80      A

In [ ]:
# add grade
import pandas as pd
data={
    "name":["ram","sam","tom"],
    "marks":[80,90,85],
    "grades":["A","B","C"]
}
df=pd.DataFrame(data)

In [40]:
# rename col
df.rename(columns={"marks":"score"})

  name  score grades
0  ram     80      A
1  sam     90      B
2  tom     85      C

In [45]:
# show datatype
df.dtypes

name        str
marks     int64
grades      str
dtype: object