PANDAS CONCATENATION AND INDEXING are used constantly when combining datasets or selecting data

PANDAS CONCATENATION = joining multiple data frames

In [1]:
# CONCATENATE ROWS (axis=0)

import pandas as pd
df1=pd.DataFrame({
    "name":["A","B"],
    "age":[20,21]
})
df2=pd.DataFrame({
    "name":["C","D"],
    "age":[22,23]
})
result=pd.concat([df1,df2])
print(result)

  name  age
0    A   20
1    B   21
0    C   22
1    D   23

In [2]:
# CONCATENATE COLUMNS (axis=1)

result=pd.concat([df1,df2],axis=1)
print(result)

  name  age name  age
0    A   20    C   22
1    B   21    D   23

In [3]:
# using ignore_index=True , we get index as sequence
result=pd.concat([df1,df2],ignore_index=True)
print(result)

  name  age
0    A   20
1    B   21
2    C   22
3    D   23

PANDAS INDEXING

INDEXING = selecting data

there are 2 main methods 

1) .loc - label based indexing

syntax : df.loc[row_label,column_label]

In [4]:
# example :
df=pd.DataFrame({
    "name":["A","B","C"],
    "marks":[80,90,85]
})
print(df.loc[1])

name      B
marks    90
Name: 1, dtype: object

In [5]:
# select specific value
df.loc[2,"marks"]

np.int64(85)

2. iloc - position based indexing

- df.iloc[row_position,col_position]

In [6]:
# example :
df.iloc[0]

name      A
marks    80
Name: 0, dtype: object

In [7]:
# select specific value :
df.iloc[1,1]

np.int64(90)

PRACTICE

In [ ]:
# concatenate rows
import pandas as pd
df1=pd.DataFrame({
    "name":["A","B"],
    "marks":[80,90]
})
df2=pd.DataFrame({
    "name":["C"],
    "marks":[85]
})
pd.concat([df1,df2])

  name  marks
0    A     80
1    B     90
0    C     85

In [10]:
# concatenate columns
import pandas as pd
df1=pd.DataFrame({
    "name":["A","B"]
})
df2=pd.DataFrame({
    "marks":[80,90]
})
pd.concat([df1,df2],axis=1)

  name  marks
0    A     80
1    B     90

In [12]:
# reset index after concatenation
pd.concat([df1,df2],ignore_index=True)

  name  marks
0    A    NaN
1    B    NaN
2  NaN   80.0
3  NaN   90.0

In [13]:
# using loc find age of sam
df=pd.DataFrame({
    "name":["ram","sam","tom"],
    "age":[21,22,23]
})
df.loc[1]

name    sam
age      22
Name: 1, dtype: object

In [14]:
# using iloc
df.iloc[2,1]

np.int64(23)

PANDAS DATAFRAMES SERIES

-SERIES : a series is a single column of data

In [2]:
import pandas as pd
data=[10,20,30,40]
s=pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
# SERIES WITH CUSTOM INDEX
import pandas as pd
marks=[80,90,85]
s=pd.Series(marks,index=["ram","sam","tom"])
print(s)

ram    80
sam    90
tom    85
dtype: int64

DATAFRAME IN PANDAS

- DATAFRAME is a table(rows+columns)

- it is made of multiple series

In [4]:
import pandas as pd
data={
    "name":["ram","sam","tom"],
    "marks":[80,90,85]
}
df=pd.DataFrame(data)
print(df)

  name  marks
0  ram     80
1  sam     90
2  tom     85

PRACTICE

In [5]:
# create a series
import pandas as pd
d=pd.Series([10,20,30,40])
print(d)

0    10
1    20
2    30
3    40
dtype: int64

In [8]:
# create dataframe
import pandas as pd
data={
    "names":["ram","sam","tom"],
    "marks":[80,90,85]
}
df=pd.DataFrame(data)
print(df)

  names  marks
0   ram     80
1   sam     90
2   tom     85

In [9]:
# print first row
print(df.loc[0])

names    ram
marks     80
Name: 0, dtype: object

In [10]:
# print marks column
print(df["marks"])

0    80
1    90
2    85
Name: marks, dtype: int64

In [11]:
print(df.shape)

(3, 2)

In [16]:
print(df[df["marks"]>80])

  names  marks
1   sam     90
2   tom     85

In [17]:
import pandas as pd
data={
    "name":["ram","sam","tom","riya","anu"],
    "marks":[80,90,85,88,92],
    "city":["delhi","mumbai","chennai","hyderabad","pune"]
}
df=pd.DataFrame(data)

1.df.head() - show first rows

- shows first 5 rows

- used to quickly check data

2.df.tail() - show last rows

3.df.shape() - no of rows & cols

4.df.columns - column names

5.df.info() - full data summary

- it shows no of rows,cols,data types,missing values

In [18]:
print(df.head(3))

  name  marks     city
0  ram     80    delhi
1  sam     90   mumbai
2  tom     85  chennai

In [19]:
print(df.tail(2))

   name  marks       city
3  riya     88  hyderabad
4   anu     92       pune

In [20]:
print(df.shape)

(5, 3)