5 categories

1. DATA INSPECTION COMMANDS

In [ ]:
import pandas as pd
df=pd.read_csv("data_csv")            # used to read a file

read_csv() - it reads a csv file(comma separated value) & converts it into dataframe

df.head() - shows first 5 rows

df.tail() - shows last 5 rows

df.shape() - returns (row,col)

2. SELECTING DATA 

df["column"] - selects 1 column

df[["col1,"col2"]] - select multiple columns

df.loc[0] - select row by label

df.iloc[0] - select row by position

3. FILTERING DATA

df[df["col"]>100]

df[df["col2"]=="place"]

df[(df["col"]>100) & (df["col"]=="place")]

4. GROUPING AND AGGREGATION

df.groupby("col").sum() - df.groupby("city")["sales"].sum() # finds the sum

df.groupby("col").mean() - finds the avg

df.groupby("col").count() - counts the no of times

df.groupby("col").max() - finds the max 

df.groupby("col").min() - finds the min

5. DATA CLEANING

df.isnull() - shows missing values per col , it returns True if value is missing else False

df.isnull.sum() - counts how many missing values are in each col

df.dropna() - removes rows that contains missing values

df.fillna() - replaces missing values with smtg

df.drop_duplicates() - remove duplicate rows

PRACTICE

In [3]:
import pandas as pd
data={
    "name":["ram","sam","tom","ram"],
    "marks":[80,90,75,80],
    "city":["delhi","mumbai","delhi","delhi"]
} 
df=pd.DataFrame(data)

In [ ]:
#1 show first 5 rows
df.head(5)

  name  marks    city
0  ram     80   delhi
1  sam     90  mumbai
2  tom     75   delhi
3  ram     80   delhi

In [5]:
#2 show shape
df.shape

(4, 3)

In [10]:
#3 select marks column
df["marks"]

0    80
1    90
2    75
3    80
Name: marks, dtype: int64

In [12]:
#4 filter students with marks>80
df[df["marks"]>80]

  name  marks    city
1  sam     90  mumbai

In [18]:
#5 find average marks
df["marks"].mean()

np.float64(81.25)

In [19]:
#6 count students per city
df.groupby("city").count()

        name  marks
city
delhi      3      3
mumbai     1      1

In [21]:
#7 remove duplicates row
df.drop_duplicates()

  name  marks    city
0  ram     80   delhi
1  sam     90  mumbai
2  tom     75   delhi